#Dockerfile of the crackit parser
#Based on Python 3
#

FROM python:3

WORKDIR /code

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY parser.py ./

CMD ["python","parser.py"]
