version: '3'
services:
    crawler:
        image: "crawler_docker"
        networks: 
            - "messages"
            - "database"
        depends_on:
            - db
            - rabbitmq
        build:
            context: ../crawler_docker
            dockerfile: dockerfile
    db:
        image: "mariadb_docker"
        networks: 
            - "database"
        build:
            context: ../mariadb_docker
            dockerfile: dockerfile
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_DATABASE: "crack_it"
            MYSQL_USER: "python"
            MYSQL_PASSWORD: "pythonpython"
        volumes:
            - "../db:/var/lib/mysql"
    rabbitmq:
        image: "rabbitmq"
        networks: 
            - "messages"
    nginx:
        image: "nginx"
        ports:
            - "8080:80"
        volumes:
            - ../web:/code
            - ../web_docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        networks: 
            - "web"
    php:
        image: "php"
        build:
            context: ../web_docker/php
            dockerfile: dockerfile
        volumes:
            - ../web:/code
        depends_on:
            - db
        networks: 
            - "database"
            - "web"
networks:
    messages:
    database:
    web:
volumes:
    web:
    db: