#Dockerfile of the crackit hacker
#Based on Python 3
#

FROM python:3

RUN apt-get update && apt-get install -y hashcat

WORKDIR /code

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY cracker.py ./

CMD ["python","cracker.py"]
