#Dockerfile of the crackit db compiler
#Based on Python 3
#

FROM python:3

RUN apt-get update 

WORKDIR /code

COPY requirements.txt ./

RUN apt-get update && apt-get install -y libcrack2 cracklib-runtime && pip install -r requirements.txt

COPY compiler.py ./

CMD ["python","compiler.py"]
